name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      metadata: read

    steps:
      - uses: actions/checkout@v4

      - name: Generate Language Card
        uses: lowlighter/metrics@latest
        with:
          filename: profile/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}

          base: ""
          plugin_languages: yes

          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          config_timezone: Europe/Dublin

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push